### PR TITLE
fix(config): add default ansi config

### LINKED ISSUE #28: error with `ansi` args when load theme
https://github.com/everviolet/nvim/blob/99c96fb681512531222c309206f94b6f97ee68d7/lua/evergarden/init.lua#L41
https://github.com/everviolet/nvim/blob/99c96fb681512531222c309206f94b6f97ee68d7/lua/evergarden/config.lua#L239

this `cfg.theme.ansi` can not pass into `evergarden.load`, because there is no default `ansi` config.

### PR DESCRIPTION
**Pull request by Parsifa1**
fix #28

### CODE REVIEW

File: lua/evergarden/config.lua [hunk 1]
```diff
@@ -146,6 +146,7 @@ local H = {}
 ---@text # Default ~
 M.default = {
   theme = {
+    ansi = false,
```
Comment (comfysage) [inline lua/evergarden/config.lua]: move below the accent option (same as in the luadoc)

**Review by comfysage — CHANGES_REQUESTED** [review]
thnx for the quick pr <3

File: lua/evergarden/config.lua (hunk 1 above)
Comment (Parsifa1) [reply lua/evergarden/config.lua]: ok!
